global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'opas-services'
    static_configs:
      - targets: ['localhost:8000', 'localhost:3000', 'localhost:16686']
